spring:
  application:
    name: notification-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz_notification
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  kafka:
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.quizz.notificationservice.event.AnswerTimeAddedEvent
    bootstrap-servers: localhost:9092

server:
  port: 8086

logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        description:
          sql: trace