eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #lesson-service-route
      routes[0]:
        id: lesson-service
        uri: lb://lesson-service
        predicates[0]: Path=/api/v1/lesson/**
      routes[1]:
        id: room-service
        uri: lb://room-service
        predicates[0]: Path=/api/v1/room/**
      routes[2]:
        id: notification-service
        uri: lb://notification-service
        predicates[0]: Path=/api/v1/notification/**
      routes[3]:
        uri: http://localhost:8761
        filters[0]: SetPath=/
        id: discovery-server
        predicates[0]: Path=/eureka/web
      routes[4]:
        id: discovery-server-static
        predicates[0]: Path=/eureka/**
        uri: http://localhost:8761
      routes[5]:
        id: asynchronous-test-service
        uri: http://localhost:8087
        filters[0]: SetPath=/
        predicates[0]: Path=/synchronous-test
      routes[6]:
        id: asynchronous-test-static
        uri: http://localhost:8087
        predicates[0]: Path=/**
      routes[7]:
        id: live-test-service
        uri: http://localhost:8088
        filters[0]: SetPath=/
        predicates[0]: Path=/live-test
      routes[8]:
        id: live-test-static
        uri: http://localhost:8088
        predicates[0]: Path=/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/oauth2-microservice-realm

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionRouteLocator: INFO
            nodeValue: TRACE
    root: INFO