spring:
  application:
    name: room-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz_room
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.quizz.roomservice.event.AnswerTimeAddedEvent
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: notificationTopic
    bootstrap-servers: localhost:9092

logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        description:
          sql: trace
server:
  port: 8083


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
